REGEX_INPUT_TAG = "regex_input"
MAX_ATTEMPT_INPUT_TAG = "max_attempts_input"
OUTPUT_LOG_TAG = "output_log"
PYAUTOGUI_FAILSAFE_TOGGLE_TAG = "failsafe_checkbox"
PYAUTOGUI_PAUSE_TAG = "pause_input"
PERFORMANCE_LOGGING_TAG = "performance_logging_checkbox"